### ISSUE TITLE
Suggest that the author add a docker image

### ISSUE THREAD

**Issue by dpy013** [tech10/nvdaRemoteServer#1]
I recently deployed one and found that this NVDA remote server is quite good.
It would be nice to have a docker image.
We can use github's docker image feature for hosting.

**Comment by tech10** [comment]
I have no experience with Docker. I will look into this, but if anyone has a pull request, I'll check it and merge if it passes any requirements. Integration with GitHub actions or goreleaser would be helpful for this as well.

Here are a couple good goals for the Docker image.

- The Dockerfile should build a static executable.
- If possible, the Docker image should only include the executable, so as to keep it as small as possible.

**Comment by tech10** [comment]
@dingpengyu
792d5bb should bring this one step closer. Integration with goreleaser or GitHub actions is another issue entirely, but Docker images can be locally built and executed. I have tested this, and it does appear to work.

**Comment by tech10** [comment]
@dingpengyu 
v0.1.15 should have produced a docker image that should run on Linux X86_64. You can get it [here.](https://github.com/tech10/nvdaRemoteServer/packages/711567) Please let me know if there are any problems, and if this will resolve this issue.

**Comment by dpy013** [comment]
> @dingpengyu
> v0.1.15 should have produced a docker image that should run on Linux X86_64. You can get it [here.](https://github.com/tech10/nvdaRemoteServer/packages/711567) Please let me know if there are any problems, and if this will resolve this issue.

hello
The following error occurs when pulling the image:
server/nvdaremoteserver-docker
Using default tag: latest
Error response from daemon: Head https://docker.pkg.github.com/v2/tech10/nvdarem
oteserver/nvdaremoteserver-docker/manifests/latest: no basic auth credentials

**Comment by tech10** [comment]
I have also received this error. I believe you must first log in with Docker. I have found no way to modify the package settings to allow anonymous downloads, despite reading documentation on the matter for quite some time. I'm looking into migrating to the new GitHub container registry as well as upgrading the GitHub actions. Hopefully, I can get all this working correctly.

**Comment by dpy013** [comment]
> I have also received this error. I believe you must first log in with Docker. I have found no way to modify the package settings to allow anonymous downloads, despite reading documentation on the matter for quite some time. I'm looking into migrating to the new GitHub container registry as well as upgrading the GitHub actions. Hopefully, I can get all this working correctly.

Thank you for your work

**Comment by tech10** [comment]
@dingpengyu
[Try this.](https://github.com/users/tech10/packages/container/package/nvdaremoteserver-docker)
I was able to pull the image, but beyond that, I have no idea what I'm doing. Let me know if this works for you.

**Comment by dpy013** [comment]
> @dingpengyu
> [Try this.](https://github.com/users/tech10/packages/container/package/nvdaremoteserver-docker)
> I was able to pull the image, but beyond that, I have no idea what I'm doing. Let me know if this works for you.
hello tech
Thanks to your work, the docker image is now running successfully.

**Comment by tech10** [comment]
Excellent, I'm glad to hear it.

**Comment by tech10** [comment]
@dingpengyu I have updated documentation and added Docker Hub images. Since you brought this up, I thought you'd be interested in knowing this. Examples on use with Docker are in the readme. The Docker Hub image pulls will likely be easier than those in the GitHub Container Registry, considering that, at the moment, the Docker Hub image pulls will always download the latest built image.

**Comment by dpy013** [comment]
> @dingpengyu I have updated documentation and added Docker Hub images. Since you brought this up, I thought you'd be interested in knowing this. Examples on use with Docker are in the readme. The Docker Hub image pulls will likely be easier than those in the GitHub Container Registry, considering that, at the moment, the Docker Hub image pulls will always download the latest built image.

Yes I like to use docker because it's convenient and I'm running docker on my soft routes and cloud servers.

**Comment by AbdullahZubair** [comment]
Hello there.
Thanks for this. I want to have a docker compose example please?

**Comment by tech10** [comment]
@AbdullahZubair I'm not really that familiar with Docker myself, as I don't use it, even though I did manage to create a Dockerfile and automatic image deployment for this server. This one, I'd probably need some help with, since I no longer have a server with Docker to test this with.
